"""initial migration

Revision ID: 504bc07ea2ab
Revises: 
Create Date: 2025-05-26 09:36:53.647519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504bc07ea2ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejercicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('respuestas_estudiantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuestas_estudiantes', schema=None) as batch_op:
        batch_op.drop_column('valor')

    with op.batch_alter_table('ejercicios', schema=None) as batch_op:
        batch_op.drop_column('archivo_url')

    # ### end Alembic commands ###
