"""Add archivo_url to Ejercicio model

Revision ID: a5f5e64ffe26
Revises: 0d6df4fb4ff4
Create Date: 2025-05-23 08:21:09.864914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f5e64ffe26'
down_revision = '0d6df4fb4ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejercicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejercicios', schema=None) as batch_op:
        batch_op.drop_column('archivo_url')

    # ### end Alembic commands ###
